name: app-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: password_manager
          POSTGRES_USER: pm_user
          POSTGRES_PASSWORD: pm_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U pm_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: until pg_isready -h localhost -U pm_user; do echo "Waiting for Postgres..."; sleep 2; done

      - name: Run Maven Tests
        run: |
          cd Backend
          mvn -B -q test

  build-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build Backend
        run: |
          cd Backend
          mvn -B -q package -DskipTests

      - name: Archive JAR
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: Backend/target/*.jar

  docker-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd Backend
          docker build -t ghcr.io/${{ github.repository_owner }}/password-manager-backend:${{ github.sha }} .
          docker tag ghcr.io/${{ github.repository_owner }}/password-manager-backend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/password-manager-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/password-manager-backend:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/password-manager-backend:latest
